### ISSUE TITLE
Arrows Missing After First Use

### ISSUE THREAD

**Issue by ggottemo** [AkshaySG14/haystack-public#3]
Hi there, cool project. Wanted to try it out, so I opened a repo and everything was looking good - the arrow button appeared when I clicked on a dependency, and let me open a related window. The new window did not have any connecting arrows to the old one though, like the colored ones shown in the demo. I thought this may have been some weird behavior with my project or React/javascript, so I tried opening a few other repos that use C# and then Python.

Unfortunately, the arrow buttons to open related files never appeared again at all, no matter where my mouse or cursor is placed. I just get a single window. Tried in a few different files that reference each other. 

Seems like it completely broke after the first workspace was closed, although with the connecting arrows also being missing at the beginning, maybe something went wrong on the first run. Restarting the program did not fix it either. Any suggestions? Would love to test it out, I think this type of workflow would be great for navigating some of the legacy projects I work on

**Comment by AkshaySG14** [comment]
Hey! Right now arrows only connect symbol nodes i.e. it won't connect a file to a symbol for example. You could go the deepest symbol in the file to try this!

Regarding the second issue, I think the dependency arrow issue is actually because you don't have the right language servers for C# and Python.

For Python: you need to download the Python language server (just search "Python" in the extensions), as well as BasedPyright (warning that BasedPyright will absolutely litter your editor with red diagnostics).

For C#:
I think this is unfortunately impossible because C# support is pretty much locked up behind Visual Studio itself.

**Comment by AkshaySG14** [comment]
If this still doesn't work for you, I'd be happy to jump on a call to fix this.

**Comment by ggottemo** [comment]
Ah I tried again and it is working in both the python and js projects, I must not have been at the deepest level before. Thanks for the explanation! 

As for C#, maybe it's possible with the C# Dev kit extension? Microsoft released it a while ago to handle C# projects in VS Code. That uses the extension here https://github.com/dotnet/vscode-csharp for language support. Or maybe the older Omnisharp LSP, but I was unable to find an up to date stand-alone extension for it - I think now it's just part of the vscode-csharp as a setting for legacy projects.

**Comment by AkshaySG14** [comment]
I tried the C# Dev Kit extension. Unfortunately, AFAICT it does not support the Call Hierarchy LSP command, which is what we rely on. Sorry about this!
